### ISSUE TITLE
socket.connect issue

### ISSUE THREAD

**Issue by kurijov** [AndreasMadsen/riakdb#1]
https://github.com/AndreasMadsen/riakdb/blob/master/lib/node.js#L63

socket.connect must accept port and host instead of object.

https://nodejs.org/api/net.html#net_socket_connect_port_host_connectlistener

> socket.connect(port[, host][, connectListener])

**Comment by AndreasMadsen** [comment]
I'm pretty sure this is an issue with the node documentation. The `option` type `.connect` method is should be public API. See https://github.com/joyent/node/blob/master/lib/net.js#L854

It is also documented in io.js https://iojs.org/api/net.html#net_socket_connect_options_connectlistener

**Comment by kurijov** [comment]
Ahh, I see. You should update example then :)

> address: '127.0.0.1',

should be

> host: '127.0.0.1'

**Comment by AndreasMadsen** [comment]
Ah, good catch :+1: The reason why the tests worked, is because `host` defaults to `localhost` when not set.

**Comment by AndreasMadsen** [comment]
Thanks. This should be fixed now. Just write if you have any other issues.
